DROP VIEW IF EXISTS VW_SECURITY_AUTH;
DROP TABLE IF EXISTS G_PROJECT;
DROP TABLE IF EXISTS MEMBERS;
DROP TABLE IF EXISTS GROUP_ROLES;
DROP TABLE IF EXISTS GROUPS;
DROP TABLE IF EXISTS CRUD;
DROP TABLE IF EXISTS MENU;
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS PROJECT;
DROP TABLE IF EXISTS USERS;

-- 시퀀스
CREATE SEQUENCE IF NOT EXISTS JOB_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS FILES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS FILES_DETAILS_SEQ START WITH 1 INCREMENT BY 1;

-- JOB
CREATE TABLE IF NOT EXISTS JOB (
    JOB_NO INT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT CLOB,
    PRIORITY INT,
    MANAGER_ID VARCHAR(50),
    USER_ID VARCHAR(50),
    PUBLIC_ROLE INT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    ADD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PROGRESS INT DEFAULT 0,
    JOB_TYPE_NO INT,
    JOB_STATUS_NO INT,
    PROJECT_NO INT,
    PARENT_JOB_NO INT,
    FILES_NO INT
);

-- FILES
CREATE TABLE IF NOT EXISTS FILES (
    FILES_NO INT PRIMARY KEY,
    USER_ID VARCHAR(50),
    UPLOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- FILES_DETAILES
CREATE TABLE IF NOT EXISTS FILES_DETAILES (
    DETAILS_NO INT PRIMARY KEY,
    FILES_NO INT,
    FILES_NAME VARCHAR(255),
    FILES_UUID VARCHAR(255),
    FILES_SIZE BIGINT,
    FILES_TYPE VARCHAR(100),
    FILES_PATH VARCHAR(500),
    CONSTRAINT FK_FILES_TO_DETAILS FOREIGN KEY (FILES_NO) REFERENCES FILES(FILES_NO)
);

-- USERS
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID VARCHAR(50) PRIMARY KEY,
    USERNAME VARCHAR(50),
    PASSWD VARCHAR(255),
    ADMIN NUMBER(1) DEFAULT 0
);

-- PROJECT
CREATE TABLE IF NOT EXISTS PROJECT (
    PROJECT_NO NUMBER PRIMARY KEY,
    PROJECT_CODE VARCHAR(20) UNIQUE,
    PROJECT_NAME VARCHAR(100),
    STATUS NUMBER,
    START_DATE DATE,
    END_DATE DATE
);

-- GROUPS
CREATE TABLE IF NOT EXISTS GROUPS (
    GROUP_NO NUMBER PRIMARY KEY,
    GROUP_NAME VARCHAR(100),
    PROJECT_NO NUMBER,
    FOREIGN KEY (PROJECT_NO) REFERENCES PROJECT(PROJECT_NO)
);

-- G_PROJECT
CREATE TABLE IF NOT EXISTS G_PROJECT (
    GROUP_NO NUMBER,
    PROJECT_NO NUMBER,
    PM NUMBER(1) DEFAULT 0,
    PRIMARY KEY (GROUP_NO, PROJECT_NO),
    FOREIGN KEY (GROUP_NO) REFERENCES GROUPS(GROUP_NO),
    FOREIGN KEY (PROJECT_NO) REFERENCES PROJECT(PROJECT_NO)
);

-- MEMBERS
CREATE TABLE IF NOT EXISTS MEMBERS (
    MEMBER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR(50),
    GROUP_NO NUMBER,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (GROUP_NO) REFERENCES GROUPS(GROUP_NO)
);

-- ROLES
CREATE TABLE IF NOT EXISTS ROLES (
    ROLE_NO NUMBER PRIMARY KEY,
    ROLE_NAME VARCHAR(255)
);

-- GROUP_ROLES
CREATE TABLE IF NOT EXISTS GROUP_ROLES (
    ROLE_NO NUMBER,
    GROUP_NO NUMBER,
    PRIMARY KEY (ROLE_NO, GROUP_NO),
    FOREIGN KEY (ROLE_NO) REFERENCES ROLES(ROLE_NO),
    FOREIGN KEY (GROUP_NO) REFERENCES GROUPS(GROUP_NO)
);

-- MENU
CREATE TABLE IF NOT EXISTS MENU (
    MENU_ID NUMBER PRIMARY KEY,
    MENU_NAME VARCHAR(100),
    TYPE VARCHAR(500),
    URL_DATA VARCHAR(255)
);

-- CRUD
CREATE TABLE IF NOT EXISTS CRUD (
    ROLE_NO NUMBER,
    MENU_ID NUMBER,
    CRUD_READ NUMBER(1) DEFAULT 0,
    CRUD_CREATE NUMBER(1) DEFAULT 0,
    CRUD_UPDATE NUMBER(1) DEFAULT 0,
    CRUD_DELETE NUMBER(1) DEFAULT 0,
    PRIMARY KEY (ROLE_NO, MENU_ID),
    FOREIGN KEY (ROLE_NO) REFERENCES ROLES(ROLE_NO),
    FOREIGN KEY (MENU_ID) REFERENCES MENU(MENU_ID)
);

-- VIEW
CREATE OR REPLACE VIEW VW_SECURITY_AUTH AS
SELECT 
    M.USER_ID, 
    P.PROJECT_NAME, 
    GR.ROLE_NO, 
    MN.MENU_ID,
    C.CRUD_READ, 
    C.CRUD_CREATE, 
    C.CRUD_UPDATE, 
    C.CRUD_DELETE
FROM MEMBERS M
JOIN GROUP_ROLES GR ON M.GROUP_NO = GR.GROUP_NO
JOIN CRUD C ON GR.ROLE_NO = C.ROLE_NO
JOIN MENU MN ON C.MENU_ID = MN.MENU_ID
JOIN PROJECT P ON MN.URL_DATA = P.PROJECT_NAME;

-- 더미 데이터
INSERT INTO GROUPS (GROUP_NO) VALUES (1);
INSERT INTO ROLES (ROLE_NO) VALUES (1);
INSERT INTO USERS (USER_ID, USERNAME, PASSWD, ADMIN) VALUES ('song', '송', '1234', 0);
INSERT INTO MEMBERS (MEMBER_NO, USER_ID, GROUP_NO) VALUES (1, 'song', 1);
INSERT INTO GROUP_ROLES (ROLE_NO, GROUP_NO) VALUES (1, 1);
INSERT INTO MENU (MENU_ID, URL_DATA) VALUES (1, 'PMS100');
INSERT INTO CRUD (ROLE_NO, MENU_ID, CRUD_READ) VALUES (1, 1, 1);
INSERT INTO PROJECT (PROJECT_NO, PROJECT_CODE, PROJECT_NAME) VALUES (1, 'PMS100', '테스트 프로젝트');
INSERT INTO GROUPS (GROUP_NO, GROUP_NAME, PROJECT_NO) VALUES (10, '개발팀', 1);
INSERT INTO MEMBERS (MEMBER_NO, USER_ID, GROUP_NO) VALUES (100, 'song', 10);
INSERT INTO G_PROJECT (GROUP_NO, PROJECT_NO, PM) VALUES (10, 1, 1);