-- 시퀀스
CREATE SEQUENCE IF NOT EXISTS JOB_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS FILES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS FILES_DETAILS_SEQ START WITH 1 INCREMENT BY 1;

-- JOB
CREATE TABLE IF NOT EXISTS JOB (
    JOB_NO INT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT CLOB,
    PRIORITY INT,
    MANAGER_ID VARCHAR(50),
    USER_ID VARCHAR(50),
    PUBLIC_ROLE INT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    ADD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PROGRESS INT DEFAULT 0,
    JOB_TYPE_NO INT,
    JOB_STATUS_NO INT,
    PROJECT_NO INT,
    PARENT_JOB_NO INT,
    FILES_NO INT -- 파일 그룹과 연결되는 외래키 역할
);

-- FILES
CREATE TABLE IF NOT EXISTS FILES (
    FILES_NO INT PRIMARY KEY,
    USER_ID VARCHAR(50),
    UPLOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- FILES_DETAILES
CREATE TABLE IF NOT EXISTS FILES_DETAILES (
    DETAILS_NO INT PRIMARY KEY,
    FILES_NO INT,
    FILES_NAME VARCHAR(255),
    FILES_UUID VARCHAR(255),
    FILES_SIZE BIGINT,
    FILES_TYPE VARCHAR(100),
    FILES_PATH VARCHAR(500),
    CONSTRAINT FK_FILES_TO_DETAILS FOREIGN KEY (FILES_NO) REFERENCES FILES(FILES_NO)
);

-- USERS
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID VARCHAR(50) PRIMARY KEY,
    USERNAME VARCHAR(50),
    PASSWD VARCHAR(255)
);